Entitas.VisualDebugging.Unity.Editor.SystemWarningThreshold = 5
Entitas.VisualDebugging.Unity.Editor.DefaultInstanceCreatorFolderPath = D:/Unity/MyProjects/VampireSurvivorsLike/src/VampireSurvivorsLike/Assets/Editor
Entitas.VisualDebugging.Unity.Editor.TypeDrawerFolderPath = D:/Unity/MyProjects/VampireSurvivorsLike/src/VampireSurvivorsLike/Assets/Editor
